ALTER TABLE public.procurement_submissions
  ADD COLUMN IF NOT EXISTS handover_to_vendor boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS handover_to_vendor_file_url text DEFAULT ''::text,
  ADD COLUMN IF NOT EXISTS vendor_name text DEFAULT ''::text,
  ADD COLUMN IF NOT EXISTS supplier_company text DEFAULT ''::text,
  ADD COLUMN IF NOT EXISTS contact_person text DEFAULT ''::text,
  ADD COLUMN IF NOT EXISTS phone_number text DEFAULT ''::text,
  ADD COLUMN IF NOT EXISTS email_address text DEFAULT ''::text,
  ADD COLUMN IF NOT EXISTS po_number text DEFAULT ''::text,
  ADD COLUMN IF NOT EXISTS po_date date,
  ADD COLUMN IF NOT EXISTS po_status text DEFAULT 'Draft'::text,
  ADD COLUMN IF NOT EXISTS material_delivery_status text DEFAULT 'Pending'::text,
  ADD COLUMN IF NOT EXISTS expected_delivery_date date,
  ADD COLUMN IF NOT EXISTS actual_delivery_date date,
  ADD COLUMN IF NOT EXISTS invoice_number text DEFAULT ''::text,
  ADD COLUMN IF NOT EXISTS payment_status text DEFAULT 'Pending'::text,
  ADD COLUMN IF NOT EXISTS procurement_status text DEFAULT 'In Progress'::text,
  ADD COLUMN IF NOT EXISTS purchase_order_doc_url text DEFAULT ''::text,
  ADD COLUMN IF NOT EXISTS delivery_note_doc_url text DEFAULT ''::text,
  ADD COLUMN IF NOT EXISTS grn_doc_url text DEFAULT ''::text,
  ADD COLUMN IF NOT EXISTS vendor_delivery_cert_doc_url text DEFAULT ''::text,
  ADD COLUMN IF NOT EXISTS material_handover_form_doc_url text DEFAULT ''::text,
  ADD COLUMN IF NOT EXISTS material_inspection_report_doc_url text DEFAULT ''::text;